### PR TITLE
font-size-snippets.md

### PR DESCRIPTION
**Pull request by AlinaTaoRao**
using rem unit to set font size.
### General Checks

- [ ] the branch is up to date with `main`/`master`
- [ ] the code works when pulled and run locally
- [ ] All CI checks pass
- [ ] all conflicts are resolved (if any)
- [ ] PR has a descriptive title
- [ ] PR has appropriate labels and milestones for easy identification
- [ ] PR it is assigned to the owner
- [ ] reviewers are assigned
- [ ] the PR contributes only one focused change
- [ ] It is in the appropriate column in the project board (if necessary)
- [ ] has short and clear description
- [ ] is linked to an issue (if it is related)
- [ ] feedback is addressed (if any and if it is appropriate feedback.)

### Markdown

- [ ] the markdown source is formatted
- [ ] spelling and grammar is correct in all text
- [ ] The markdown looks correct when you preview the file
- [ ] all links and images work
- [ ] any embedded code snippets are formatted

### CODE REVIEW

**Comment by AlinaTaoRao** [comment]
I can't pass the PR checks. Look into the details,  I think it's not my responsibility to edit the files from the errors , right?  How can I solve this problem.  Is it a problem from my branch alina-sni-text-size?
All checks have failed
?

**Review by gelilaa — CHANGES_REQUESTED** [review]
hey @AlinaTaoRao the problem that you are facing has been fixed. can you please make a small edit and push again?

**Comment by AlinaTaoRao** [comment]
@gelilaa 
Yeah, sure. Please check it again. 😄

**Review by gelilaa — APPROVED** [review]
great!

**Pull request merged**
