### PR TITLE
update web-development-vocabulary.md

### PR DESCRIPTION
**Pull request by AlinaTaoRao**
update /vocabulary/web-development-vocabulary.md to include backlog
related #59
### General Checks

- [ ] the branch is up to date with `main`/`master`
- [ ] the code works when pulled and run locally
- [ ] All CI checks pass
- [ ] all conflicts are resolved (if any)
- [ ] PR has a descriptive title
- [ ] PR has appropriate labels and milestones for easy identification
- [ ] PR it is assigned to the owner
- [ ] reviewers are assigned
- [ ] the PR contributes only one focused change
- [ ] It is in the appropriate column in the project board (if necessary)
- [ ] has short and clear description
- [ ] is linked to an issue (if it is related)
- [ ] feedback is addressed (if any and if it is appropriate feedback.)

### Markdown

- [ ] the markdown source is formatted
- [ ] spelling and grammar is correct in all text
- [ ] The markdown looks correct when you preview the file
- [ ] all links and images work
- [ ] any embedded code snippets are formatted

### CODE REVIEW

**Comment by AlinaTaoRao** [comment]
I can't pass the PR checks. Look into the details,  I think it's not my responsibility to edit the files from the errors , right?  How can I solve this problem.  Is it a problem from my branch alina-voc-agile
All checks have failed
?

**Review by gelilaa — CHANGES_REQUESTED** [review]
hey @AlinaTaoRao, great job! The errors that you are facing now have been fixed. we are trying to keep the vocabulary to 500 words per student. can you please edit yours so it can fit that as well?

P.S. you don't have to create a new branch for editing your document 😉

**Comment by AlinaTaoRao** [comment]
@gelilaa 
Thanks for your hard work to fix the problem. 👍 

> we are trying to keep the vocabulary to 500 words per student. can you please edit yours so it can fit that as well?

About 500 words. Do you mean the key words, or the whole words in a markdown file?
If you mean the key words. At present my vocabulary is far more less than 500 words. I need to add more in the future. 😄

**Comment by gelilaa** [comment]
> About 500 words. Do you mean the key words, or the whole words in a markdown file?

I was talking about the whole words. It is ok for now but for the next module keep in mind to not pass the limit

**Review by gelilaa — APPROVED** [review]

**Comment by AlinaTaoRao** [comment]
@gelilaa 
Now I see. Next time I will keep the whole words less than 500. 😄

**Pull request merged**
