### PR TITLE
adding snippet and vocabulary

### PR DESCRIPTION
**Pull request by sannesofie**
### General Checks

- [x] the branch is up to date with `main`/`master`
- [x] the code works when pulled and run locally
- [x] All CI checks pass
- [x] all conflicts are resolved (if any)
- [x] PR has a descriptive title
- [x] PR has appropriate labels and milestones for easy identification
- [x] PR it is assigned to the owner
- [x] reviewers are assigned
- [x] the PR contributes only one focused change
- [x] It is in the appropriate column in the project board (if necessary)
- [x] has short and clear description
- [x] is linked to an issue (if it is related)
- [x] feedback is addressed (if any and if it is appropriate feedback.)

### Markdown

- [ ] the markdown source is formatted
- [x] spelling and grammar is correct in all text
- [x] The markdown looks correct when you preview the file
- [ ] all links and images work
- [ ] any embedded code snippets are formatted

### CODE REVIEW

**Comment by sannesofie** [comment]
@gelilaa I am always having trouble with lint when trying to PR to anything other than my own repository and when looking at the details and I try to fix it it still does not work. It is difficult for me to understand the problem in the details.
Hope you have some insight

**Comment by arnochauveau** [comment]
> @gelilaa I am always having trouble with lint when trying to PR to anything other than my own repository and when looking at the details and I try to fix it it still does not work. It is difficult for me to understand the problem in the details. Hope you have some insight

You can always click 'details' to check out the error message 

image

It looks like this is the error

image

According to the documentation of ls-lint (https://ls-lint.org/1.x/configuration/the-rules.html#overview) kebab-case means only lowercase letters, numbers and dashes(-) are allowed. So you'll have to rename your file vocabulary/Favicon-html.md to have a lowercase F.

image

**Comment by sannesofie** [comment]
@arnochauveau At the end I came to the same conclusion after Googling for a bit, I changed it and did another push, but still seems like the problem is there... maybe Github is slow... I will try again shortly 🤞

**Comment by arnochauveau** [comment]
> @arnochauveau At the end I came to the same conclusion after Googling for a bit, I changed it and did another push, but still seems like the problem is there... maybe Github is slow... I will try again shortly 🤞

Are you on Windows? Windows is a little weird with capitalization (capitals or no capitals are the same for windows) so it won't detect the change out of the box. 

You can try running  `git config core.ignorecase false` in you command prompt and it should pick it up.
If that doesn't work, you might be better off just copying the files to your desktop,  starting a new branch and pasting the files back again and then pick the right name before committing.

**Comment by sannesofie** [comment]
@arnochauveau not on Windows, on Mac... I tried the option you suggested, recloned the repo and water to add it again, but it did not clone everything... will keep working on this if nothing works by tomorrow maybe I can give you a quick call

**Comment by arnochauveau** [comment]
> @arnochauveau not on Windows, on Mac... I tried the option you suggested, recloned the repo and water to add it again, but it did not clone everything... will keep working on this if nothing works by tomorrow maybe I can give you a quick call

Yes, I'm available from 16.00 tomorrow. Just send me a slack or discord message and we can take a look.

**Pull request closed without merging**
