### PR TITLE
adding snippet responsive image

### PR DESCRIPTION
**Pull request by sannesofie**
### General Checks

- [ ] the branch is up to date with `main`/`master`
- [ ] the code works when pulled and run locally
- [ ] All CI checks pass
- [ ] all conflicts are resolved (if any)
- [ ] PR has a descriptive title
- [ ] PR has appropriate labels and milestones for easy identification
- [ ] PR it is assigned to the owner
- [ ] reviewers are assigned
- [ ] the PR contributes only one focused change
- [ ] It is in the appropriate column in the project board (if necessary)
- [ ] has short and clear description
- [ ] is linked to an issue (if it is related)
- [ ] feedback is addressed (if any and if it is appropriate feedback.)

### Markdown

- [ ] the markdown source is formatted
- [ ] spelling and grammar is correct in all text
- [ ] The markdown looks correct when you preview the file
- [ ] all links and images work
- [ ] any embedded code snippets are formatted

### CODE REVIEW

**Comment by arnochauveau** [comment]
Hey @sannesofie can you please revert the changes that you made to the files other than `snippets/html-css/responsive-image.md` ? 

You can revert to the version of the main branch by using the following GIT command in the CLI: 
`git checkout origin/main -- path/to/file`

The snippet looks good!

**Comment by sannesofie** [comment]
@arnochauveau I just looked over the changes and the only changes I did was add the little snippet... I do not know how all the other changes happened. I will try and revert

**Comment by arnochauveau** [comment]
> @arnochauveau I just looked over the changes and the only changes I did was add the little snippet... I do not know how all the other changes happened. I will try and revert

That happens sometimes :-) 
That's why I always check what files changed and revert the accidental changes before committing.

**Comment by sannesofie** [comment]
@arnochauveau Is it normal that VScode just adds changes by auto?
I tried git checkout origin/main -- path/to/file (not sure how to do this) can you help?

**Comment by arnochauveau** [comment]
> @arnochauveau Is it normal that VScode just adds changes by auto? I tried git checkout origin/main -- path/to/file (not sure how to do this) can you help?

Sure, I've contacted you via Discord!

**Review by arnochauveau — APPROVED** [review]

**Pull request merged**
